#tcp://172.28.19.97:61616
spring:
  activemq:
    broker-url: nio://localhost:61608
    close-timeout:  18s
    user: admin
    password: admin

  jms:
    pub-sub-domain: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/pritise?characterEncoding=utf-8


myqueue: boot-active-queue
