spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/pritise?characterEncoding=utf-8
#logging:
#  file: mylogs.log
#  path: D:/mylogs
#


mybatis:
  mapper-locations:
    - classpath*:com/hangyan/redis_study/Mapper/**/*.xml