



#  spring.activemq.broker-url=tcp://127.0.0.1:61616
#    # 在考虑结束之前等待的时间
#    #spring.activemq.close-timeout=15s
#    # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
#    spring.activemq.in-memory=true
#    # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留。
#    spring.activemq.non-blocking-redelivery=false
#    # 等待消息发送响应的时间。设置为0等待永远。
#    spring.activemq.send-timeout=0
#    #默认情况下activemq提供的是queue模式，若要使用topic模式需要配置下面配置
#    spring.jms.pub-sub-domain=true
#    #账号
#    spring.activemq.user=admin
#    # 密码
#    spring.activemq.password=admin
spring:
  activemq:
    broker-url: tcp://localhost:61616
    close-timeout: 15s
    in-memory: true
    non-blocking-redelivery: false
    send-timeout: 0
    user: admin
    password: admin
  jms:
    pub-sub-domain: false

#自己定义的队列名称
myqueue: boot-active-queue
