

mybatis:
  mapper-locations:
    - classpath*:com/hangyan/tokenStudy/service/Mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/pritise?characterEncoding=utf-8
logging:
  file: D:/a.log